"""mcapi-auth — Microsoft → Minecraft auth **and** Mojang REST APIs.
A single async, typed Python library that covers:

* :mod:`mcapi_auth.auth` — the 5-stage Microsoft → Mojang token chain
  (device-code OAuth, refresh, Xbox Live, XSTS, ``loginWithXbox``) and
  related helpers (cookies-based silent flows, entitlements, joinServer,
  refresh-token storage).
* :mod:`mcapi_auth.api` — the public + authed Mojang/Minecraft REST API
  surface (UUID lookups, public profile + texture decode, blocked servers,
  authed profile / skin / cape / name endpoints, piston-meta).

The top level re-exports the everyday names from both subpackages so the
common case is a one-liner::

    import asyncio
    from mcapi_auth import login, get_own_profile

    async def main() -> None:
        session = await login()
        profile = await get_own_profile(session)
        print(profile.name, profile.id)

    asyncio.run(main())

For finer-grained access, import directly from
:mod:`mcapi_auth.auth` / :mod:`mcapi_auth.api`.
"""

import logging
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from . import api, auth
from .api import (
    CapeEntry,
    CapeTexture,
    DecodedTextures,
    DownloadEntry,
    NameAvailability,
    NameChangeEligibility,
    NameLookupResult,
    OwnProfile,
    ProfileProperty,
    PublicProfile,
    SkinEntry,
    SkinModel,
    SkinTexture,
    SkinVariant,
    TokenLike,
    VersionDetails,
    VersionEntry,
    VersionManifest,
    change_cape,
    change_name,
    change_skin_from_file,
    change_skin_from_url,
    check_name_availability,
    coerce_token,
    decode_texture_property,
    disable_cape,
    extract_textures,
    fetch_blocked_servers,
    fetch_version_manifest,
    get_name_change_eligibility,
    get_own_profile,
    get_profile_by_uuid,
    get_uuid_by_name,
    get_uuids_by_names,
    hostname_variants,
    is_blocked,
    is_server_blocked,
    reset_skin,
)
from .auth import (
    BEDROCK_ANDROID_CLIENT_ID,
    BEDROCK_IOS_CLIENT_ID,
    BEDROCK_NINTENDO_CLIENT_ID,
    BEDROCK_PLAYSTATION_CLIENT_ID,
    BEDROCK_WIN32_CLIENT_ID,
    EDU_CLIENT_ID,
    KNOWN_CLIENT_IDS,
    KNOWN_CLIENT_REDIRECTS,
    LIQUIDLAUNCHER_CLIENT_ID,
    LIVE_CONNECT_DESKTOP_REDIRECT_URI,
    MINECRAFT_LAUNCHER_CLIENT_ID,
    MINECRAFT_LAUNCHER_V1_CLIENT_ID,
    OFFICE365_API_EDITOR_CLIENT_ID,
    PRISM_LAUNCHER_CLIENT_ID,
    PRISM_LAUNCHER_REDIRECT_URI,
    XBOX_APP_IOS_CLIENT_ID,
    XBOX_GAMEPASS_IOS_CLIENT_ID,
    BrowserCookie,
    CookieAuthError,
    DeviceCodeCallback,
    DeviceCodePrompt,
    Entitlements,
    FileTokenStorage,
    JoinServerError,
    MinecraftSession,
    MinecraftTokenInfo,
    MSATokens,
    NullTokenStorage,
    PKCEChallenge,
    SISUTokens,
    TokenStorage,
    XboxLiveToken,
    XSTSToken,
    acquire_msa_via_browser,
    acquire_msa_via_browser_v1,
    authenticate_xbl,
    authenticate_xsts,
    build_authorize_url,
    cookies_to_header,
    create_pkce_challenge,
    decode_minecraft_access_token,
    default_storage_path,
    derive_entitlement_flags,
    exchange_authorization_code,
    exchange_refresh_token,
    extract_sisu_token,
    fetch_entitlements,
    is_v1_client_id,
    join_server,
    login,
    login_via_browser,
    login_via_browser_v1,
    login_with_cookies_msa_v1,
    login_with_cookies_prism,
    login_with_cookies_sisu,
    login_with_xbox,
    poll_for_device_code_token,
    request_device_code,
    resolve_browser_redirect,
    resolve_client_id,
)
from .exceptions import (
    AdultVerificationRequiredError,
    AuthorizationDeclinedError,
    BadRequestError,
    ChildAccountError,
    DeviceCodeExpiredError,
    ForbiddenError,
    HttpError,
    InvalidProfileError,
    McApiAuthError,
    McApiError,
    McAuthError,
    MinecraftAuthError,
    MinecraftProfileNotFoundError,
    MSAAuthError,
    MSAFlowError,
    NameNotAllowedError,
    NameTakenError,
    NotFoundError,
    NoXboxAccountError,
    RateLimitedError,
    RegionBlockedError,
    TooManyNamesError,
    UnauthorizedError,
    VerifyAgeRequiredError,
    XboxAuthError,
    XSTSError,
    xerr_to_exception,
)

# PEP 8 / library convention — install a NullHandler so users without
# configured logging don't see "no handlers found" warnings.
logging.getLogger(__name__).addHandler(logging.NullHandler())

try:
    __version__ = _pkg_version("mcapi-auth")
except PackageNotFoundError:  # editable / source checkout
    __version__ = "0.0.0+unknown"

__all__ = [
    "BEDROCK_ANDROID_CLIENT_ID",
    "BEDROCK_IOS_CLIENT_ID",
    "BEDROCK_NINTENDO_CLIENT_ID",
    "BEDROCK_PLAYSTATION_CLIENT_ID",
    "BEDROCK_WIN32_CLIENT_ID",
    "EDU_CLIENT_ID",
    "KNOWN_CLIENT_IDS",
    "KNOWN_CLIENT_REDIRECTS",
    "LIQUIDLAUNCHER_CLIENT_ID",
    "LIVE_CONNECT_DESKTOP_REDIRECT_URI",
    "MINECRAFT_LAUNCHER_CLIENT_ID",
    "MINECRAFT_LAUNCHER_V1_CLIENT_ID",
    "OFFICE365_API_EDITOR_CLIENT_ID",
    "PRISM_LAUNCHER_CLIENT_ID",
    "PRISM_LAUNCHER_REDIRECT_URI",
    "XBOX_APP_IOS_CLIENT_ID",
    "XBOX_GAMEPASS_IOS_CLIENT_ID",
    "AdultVerificationRequiredError",
    "AuthorizationDeclinedError",
    "BadRequestError",
    "BrowserCookie",
    "CapeEntry",
    "CapeTexture",
    "ChildAccountError",
    "CookieAuthError",
    "DecodedTextures",
    "DeviceCodeCallback",
    "DeviceCodeExpiredError",
    "DeviceCodePrompt",
    "DownloadEntry",
    "Entitlements",
    "FileTokenStorage",
    "ForbiddenError",
    "HttpError",
    "InvalidProfileError",
    "JoinServerError",
    "MSAAuthError",
    "MSAFlowError",
    "MSATokens",
    "McApiAuthError",
    "McApiError",
    "McAuthError",
    "MinecraftAuthError",
    "MinecraftProfileNotFoundError",
    "MinecraftSession",
    "MinecraftTokenInfo",
    "NameAvailability",
    "NameChangeEligibility",
    "NameLookupResult",
    "NameNotAllowedError",
    "NameTakenError",
    "NoXboxAccountError",
    "NotFoundError",
    "NullTokenStorage",
    "OwnProfile",
    "PKCEChallenge",
    "ProfileProperty",
    "PublicProfile",
    "RateLimitedError",
    "RegionBlockedError",
    "SISUTokens",
    "SkinEntry",
    "SkinModel",
    "SkinTexture",
    "SkinVariant",
    "TokenLike",
    "TokenStorage",
    "TooManyNamesError",
    "UnauthorizedError",
    "VerifyAgeRequiredError",
    "VersionDetails",
    "VersionEntry",
    "VersionManifest",
    "XSTSError",
    "XSTSToken",
    "XboxAuthError",
    "XboxLiveToken",
    "__version__",
    "acquire_msa_via_browser",
    "acquire_msa_via_browser_v1",
    "api",
    "auth",
    "authenticate_xbl",
    "authenticate_xsts",
    "build_authorize_url",
    "change_cape",
    "change_name",
    "change_skin_from_file",
    "change_skin_from_url",
    "check_name_availability",
    "coerce_token",
    "cookies_to_header",
    "create_pkce_challenge",
    "decode_minecraft_access_token",
    "decode_texture_property",
    "default_storage_path",
    "derive_entitlement_flags",
    "disable_cape",
    "exchange_authorization_code",
    "exchange_refresh_token",
    "extract_sisu_token",
    "extract_textures",
    "fetch_blocked_servers",
    "fetch_entitlements",
    "fetch_version_manifest",
    "get_name_change_eligibility",
    "get_own_profile",
    "get_profile_by_uuid",
    "get_uuid_by_name",
    "get_uuids_by_names",
    "hostname_variants",
    "is_blocked",
    "is_server_blocked",
    "is_v1_client_id",
    "join_server",
    "login",
    "login_via_browser",
    "login_via_browser_v1",
    "login_with_cookies_msa_v1",
    "login_with_cookies_prism",
    "login_with_cookies_sisu",
    "login_with_xbox",
    "poll_for_device_code_token",
    "request_device_code",
    "reset_skin",
    "resolve_browser_redirect",
    "resolve_client_id",
    "xerr_to_exception",
]
