"""REST API surface: public lookups + authed profile/skin/cape/name ops.
The :mod:`mcapi_auth.api` subpackage owns everything related to *using*
a Minecraft access token (and the public lookup endpoints that don't
need one). Top-level convenience names are also re-exported from the
:mod:`mcapi_auth` namespace.
"""

from .._constants import (
    DEFAULT_API_USER_AGENT,
    DEFAULT_HTTP_TIMEOUT,
)
from ..exceptions import (
    BadRequestError,
    ForbiddenError,
    HttpError,
    InvalidProfileError,
    McApiError,
    NameNotAllowedError,
    NameTakenError,
    NotFoundError,
    RateLimitedError,
    TooManyNamesError,
    UnauthorizedError,
)
from ._session import TokenLike, coerce_token
from .account import (
    CapeEntry,
    NameAvailability,
    NameChangeEligibility,
    OwnProfile,
    SkinEntry,
    SkinVariant,
    change_cape,
    change_name,
    change_skin_from_file,
    change_skin_from_url,
    check_name_availability,
    disable_cape,
    get_name_change_eligibility,
    get_own_profile,
    reset_skin,
)
from .blocked_servers import (
    fetch_blocked_servers,
    hostname_variants,
    is_blocked,
    is_server_blocked,
)
from .meta import (
    DownloadEntry,
    VersionDetails,
    VersionEntry,
    VersionManifest,
    fetch_version_manifest,
)
from .player_certificates import (
    MinecraftKeyPair,
    MinecraftPlayerCertificates,
    fetch_player_certificates,
)
from .playfab import (
    BEDROCK_PLAYFAB_TITLE_ID,
    EDU_PLAYFAB_TITLE_ID,
    PlayFabEntityToken,
    PlayFabError,
    PlayFabToken,
    playfab_get_entity_token,
    playfab_login_with_xbox,
)
from .profile import (
    NameLookupResult,
    ProfileProperty,
    PublicProfile,
    get_profile_by_uuid,
    get_uuid_by_name,
    get_uuids_by_names,
)
from .realms import (
    DEFAULT_REALMS_GAME_VERSION,
    RealmsCompatibility,
    RealmsJoinInfo,
    RealmsPlayer,
    RealmsTosError,
    RealmsWorld,
    accept_realms_tos,
    fetch_realms_compatible,
    fetch_realms_join_info,
    fetch_realms_world,
    fetch_realms_worlds,
    is_realms_available,
    is_realms_tos_agreed,
)
from .textures import (
    CapeTexture,
    DecodedTextures,
    SkinModel,
    SkinTexture,
    decode_texture_property,
    extract_textures,
)

__all__ = [
    "BEDROCK_PLAYFAB_TITLE_ID",
    "DEFAULT_API_USER_AGENT",
    "DEFAULT_HTTP_TIMEOUT",
    "DEFAULT_REALMS_GAME_VERSION",
    "EDU_PLAYFAB_TITLE_ID",
    "BadRequestError",
    "CapeEntry",
    "CapeTexture",
    "DecodedTextures",
    "DownloadEntry",
    "ForbiddenError",
    "HttpError",
    "InvalidProfileError",
    "McApiError",
    "MinecraftKeyPair",
    "MinecraftPlayerCertificates",
    "NameAvailability",
    "NameChangeEligibility",
    "NameLookupResult",
    "NameNotAllowedError",
    "NameTakenError",
    "NotFoundError",
    "OwnProfile",
    "PlayFabEntityToken",
    "PlayFabError",
    "PlayFabToken",
    "ProfileProperty",
    "PublicProfile",
    "RateLimitedError",
    "RealmsCompatibility",
    "RealmsJoinInfo",
    "RealmsPlayer",
    "RealmsTosError",
    "RealmsWorld",
    "SkinEntry",
    "SkinModel",
    "SkinTexture",
    "SkinVariant",
    "TokenLike",
    "TooManyNamesError",
    "UnauthorizedError",
    "VersionDetails",
    "VersionEntry",
    "VersionManifest",
    "accept_realms_tos",
    "change_cape",
    "change_name",
    "change_skin_from_file",
    "change_skin_from_url",
    "check_name_availability",
    "coerce_token",
    "decode_texture_property",
    "disable_cape",
    "extract_textures",
    "fetch_blocked_servers",
    "fetch_player_certificates",
    "fetch_realms_compatible",
    "fetch_realms_join_info",
    "fetch_realms_world",
    "fetch_realms_worlds",
    "fetch_version_manifest",
    "get_name_change_eligibility",
    "get_own_profile",
    "get_profile_by_uuid",
    "get_uuid_by_name",
    "get_uuids_by_names",
    "hostname_variants",
    "is_blocked",
    "is_realms_available",
    "is_realms_tos_agreed",
    "is_server_blocked",
    "playfab_get_entity_token",
    "playfab_login_with_xbox",
    "reset_skin",
]
